<?php

/**
 * Implements hook_facetapi_url_processors().

 */
function facetapi_pretty_paths_facetapi_url_processors() {
  return array(
    'pretty_paths' => array(
      'handler' => array(
        'label' => t('Pretty paths'),
        'class' => 'FacetapiUrlProcessorPrettyPaths',
      ),
    ),
  );
}

/**
 * Allows for alterations to the searcher definitions.
 *
 * @param array &$searcher_info
 *   The return values of hook_facetapi_searcher_info() implementations.
 *
 * @see hook_facetapi_searcher_info()
 */
function facetapi_pretty_paths_facetapi_searcher_info_alter(array &$searcher_info) {
  foreach ($searcher_info as &$info) {
    $info['url processor'] = 'pretty_paths';
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter.
 */
function facetapi_pretty_paths_form_facetapi_facet_display_form_alter(&$form, &$form_state, $form_id) {
  // Get global facet settings.
  $adapter = $form['#facetapi']['adapter'];
  $facet_settings = $adapter->getFacetSettingsGlobal($form['#facetapi']['facet']);

  // Path alias defaults to field_api_name.
  $alias = isset($facet_settings->settings['pretty_paths_alias']) ?
    $facet_settings->settings['pretty_paths_alias'] : $form['#facetapi']['facet']['field api name'];

  // Add pretty paths alias option to global facet settings.
  $form['global']['pretty_paths_alias'] = array(
    '#type' => 'textfield',
    '#title' => t('Pretty path alias'),
    '#default_value' => $alias,
    '#description' => t('Pretty paths will be generated in the following way: &quot;&lt;alias&gt;/&lt;value&gt;&quot;. ' .
      'For taxonomy terms it outputs the id as well: &quot;&lt;alias&gt;/&lt;term-name&gt;-&lt;term-id&gt;&quot;.'),
  );
}
