<?php

/**
 * Implements hook_facetapi_url_processors().

 */
function facetapi_pretty_paths_facetapi_url_processors() {
  return array(
    'pretty_paths' => array(
      'handler' => array(
        'label' => t('Pretty paths'),
        'class' => 'FacetapiUrlProcessorPrettyPaths',
      ),
    ),
  );
}

/**
 * Allows for alterations to the searcher definitions.
 *
 * @param array &$searcher_info
 *   The return values of hook_facetapi_searcher_info() implementations.
 *
 * @see hook_facetapi_searcher_info()
 */
function facetapi_pretty_paths_facetapi_searcher_info_alter(array &$searcher_info) {
  foreach ($searcher_info as &$info) {
    $info['url processor'] = 'pretty_paths';
  }
}
